### ISSUE TITLE
pod names

### ISSUE THREAD

**Issue by caduceus4** [tinyzimmer/kvdi#16]
Is there a way to have the pod names be specific to the user? Currently you have them as desktop-somehexstring. It would be nice to have them as desktop-user1-0, desktop-user1-1, desktop-user2-0, desktop-user2-1 (if more than one allowed per user). That way, an admin can quickly hunt down a pod and kill or connect to it as necessary. Thx

**Comment by tinyzimmer** [comment]
There should be a label with the username on the Desktop or Pod object so you could select based off that.

When I'm looking into the other thing I'll look into this.

**Comment by tinyzimmer** [comment]
After looking into this further, I'm leaning on "Won't Do". It's relatively easy to grab the pods or desktops for a given user with something like this:

```bash
$ kubectl get desktop -l desktopUser=admin
NAME               AGE
ubuntu-xfce6gbqp   41s

$ kubectl get pod -l desktopUser=admin
NAME               READY   STATUS    RESTARTS   AGE
ubuntu-xfce6gbqp   2/2     Running   0          55s
```

Where I'm hesitant to put the username in the NAME itself, is that those names have to be DNS-compliant, and a username could contain characters that wouldn't work. I could go the opt-in approach, but every auth provider will potentially produce bugs with something like this since none of them can be guaranteed to have compliant usernames.
