### ISSUE TITLE
closing a tab with a kvdi session in it makes it disappear

### ISSUE THREAD

**Issue by nikhiljha** [tinyzimmer/kvdi#7]
I accidentally closed my Firefox tab while using a desktop. The desktop is still running (it shows up in `kubectl get pods`), but it no longer shows up in the UI, so I can't get back into it.

Ended up completely removing and then reinstalling kVDI to get rid of it.

**Comment by tinyzimmer** [comment]
Hey @nikhiljha 

Thanks for trying it out! Yea, this is actually one issue I know about, and I haven't found a good way to fix yet, but I'll take another look at it sometime this week.

FWIW, when this happens, you need to look for the `Desktop` resource to delete (`kubectl get desktops`), not the pod. Otherwise the `Desktop` will just keep recreating it.

**Comment by tinyzimmer** [comment]
Just chiming in that I haven't forgotten about this. A combination of new job and personal crises has had me focused on other things the past few weeks.

I'll just say that if anyone comes across this and wants to open a PR before I get to it, I'll be happy to take a look at it.

**Comment by tinyzimmer** [comment]
Taking a stab at this this weekend
